### ISSUE TITLE
Cannot unpickle in __main__ in Python 2

### ISSUE THREAD

**Issue by lordmauve** [lordmauve/chopsticks#7]
Trying to pass a function in `__main__` to the remote agent in Python 2 causes 

```
ErrorResult(u'Host \'worker-1\' raised exception; traceback follows\n\n    Traceback (most recent call last):\n      File "bubble.py", line 144, in wrapper\n      File "bubble.py", line 160, in handle_call_thread\n    ImportError: Cannot re-init internal module __main__')
```

**Comment by Ian2020** [comment]
Hi, great project. Is there any workaround for this issue?

**Comment by lordmauve** [comment]
There are several. The cleanest one is is to make sure that the functions you want to call remotely are in a separate module to your __main__ module. This is good organisational practice anyway.

**Comment by Ian2020** [comment]
Sorry, I should have thought of that before I posted! Thanks very much.

**Comment by lordmauve** [comment]
If you want a single-file solution, there is one, but it's subtle and cludgey:

Say your script is called `my_script.py`:

    def my_remote_func():
        ...

    if __name__ == '__main__':
        from my_script import my_remote_func
        # now my_remote_func is my_script.my_remote_func, which can be unpickled
        from chopsticks.tunnel import Tunnel
        Tunnel(hostname).call(my_remote_func)

**Comment by Ian2020** [comment]
Very kind of you to provide that snippet - I will use it. Just trying out Chopsticks quickly for first time today and was too lazy to use modules! It's already saved me some time.

**Comment by romanlevin** [comment]
The same (or a very similar) issue exists in Python 3, which a much less friendly error:

```
chopsticks.tunnel.RemoteException: Host 'local' raised exception; traceback follows

    Traceback (most recent call last):
      File "bubble.py", line 139, in wrapper
      File "bubble.py", line 152, in handle_call_thread
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "bubble.py", line 119, in load_module
      File "controller://run.py", line 3, in <module>
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "bubble.py", line 119, in load_module
      File "controller://chopsticks/tunnel.py", line 358, in <module>
        class SubprocessTunnel(PipeTunnel):
      File "controller://chopsticks/tunnel.py", line 366, in SubprocessTunnel
        '__bubble = sys.stdin.read(%d); ' % len(bubble) +
    TypeError: object of type 'NoneType' has no len()
```

**Comment by lordmauve** [comment]
@romanlevin - that's actually caused by issue #6.

Specifically, issue #6 means you can't import chopsticks on the remote host at the moment. If you move your chopsticks imports to the `if __name__ == __main__` block, then it should work.

**Comment by romanlevin** [comment]
@lordmauve oh I see, thanks!

**Comment by lordmauve** [comment]
The solution to issue #17 will fix this issue also.
